app1/urls.py
from app1.views import *
from django.urls import path

app_name='xyz'
urlpatterns=[
    path('a/',a,name='a'),
]

app2/urls.py
from app2.views import *
from django.urls import path

app_name='pqr'
urlpatterns=[
    path('b/',b,name='b'),
]

project9/urls.py
from django.contrib import admin
from django.urls import path,include
import app1,app2

urlpatterns = [
    path('admin/', admin.site.urls),
    path('app1/',include('app1.urls')),
    path('app2/',include('app2.urls')),
]

app1/models.py
from django.db import models

# Create your models here.

app2/models.py
from django.db import models

# Create your models here.

app1/views.py
from django.shortcuts import render

# Create your views here.
def a(request):
    return render(request,'a.html')

app2/views.py
from django.shortcuts import render

# Create your views here.
def b(request):
    return render(request,'b.html')

templates/a.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>Hii</h1>
        <a href="{% url 'pqr:b' %}"><h3>Waiting for reply</h3></a>
    </center>
</body>
</html>

templates/b.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>hloo</h1>
        <a href="{% url 'xyz:a' %}"><h3>response</h3></a>
    </center>
</body>
</html>